name: CI Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8 Linting
      run: flake8 .

  test:
    name: Run unit tests with nose2
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose2

    - name: Ensure `tests/` exists
      run: |
        if [ ! -d "tests" ]; then echo "No tests directory found"; exit 1; fi
        touch tests/__init__.py  # Ensure tests is a package

    - name: Run Nose2 Tests
      run: nose2 -v
